### ISSUE TITLE
readlink: illegal option -- f , can't open file ...

### ISSUE THREAD

**Issue by JBetbe** [Plattar/python-xrutils#1]
I've been trying to work with your Docker build to convert a .gltf file to .usdz but I had no luck :(
I think all is running correctly but this error is showing to me:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
python: can't open file '/xrutils_fixgltf.py': [Errno 2] No such file or directory
python: can't open file '/../xrutils/gltf2usd/Source/gltf2usd.py': [Errno 2] No such file or directory

**Comment by DavidArayan** [comment]
Hello @Betbe,

Sounds like a pathing issue, It looks like some of the scripts are trying to be opened and failing. We have't ran into this issue ourselves. Would you mind providing the exact command's that you're running so we can replicate the problem locally?

**Comment by krnbatta** [comment]
I was facing a similar issue. Thanks, @DavidArayan. That worked like charm! 👯‍♂️

**Comment by JBetbe** [comment]
Is this a bug? Someone has got the similar issue, right?
